Release version 2.0.560

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -8,6 +8,27 @@ if [[ $1 = clean ]]; then
 elif [[ $1 = hiera ]]; then
     shift
     exec clojure -X:hiera graph "$@"
+elif [[ $1 = deploy ]]; then
+    shift
+    if [[ -f ~/.clojure/clojars.env ]]; then
+        source ~/.clojure/clojars.env
+    fi
+    if [[ -z $CLOJARS_USERNAME ]]; then
+        read -p "Clojars username: " CLOJARS_USERNAME
+        if [[ -z $CLOJARS_USERNAME ]]; then
+            echo "No username available, aborting" >&2
+            exit 1
+        fi
+    fi
+    if [[ -z $CLOJARS_PASSWORD ]]; then
+        read -p "Clojars deploy token: " CLOJARS_PASSWORD
+        if [[ -z $CLOJARS_PASSWORD ]]; then
+            echo "No deploy token available, aborting" >&2
+            exit 1
+        fi
+    fi
+    export CLOJARS_USERNAME CLOJARS_PASSWORD
+    exec clojure -T:build deploy "$@"
 else
     exec clojure -T:build "$@"
 fi
